### PR TITLE
Add config for Travis continuous integration

### PR DESCRIPTION
**Pull request by mkllnk**
https://github.com/openfoodfoundation/openfoodnetwork/issues/2286

This version passed all active specs for my fork: https://travis-ci.org/mkllnk/spree/builds/400199170

I tried using postgres instead of sqlite, but encountered another gem version conflict. There is definitely room for improvement, but I thought that we should have CI running as quickly as possible to detect any additional failures.

More tasks:

- fix the specs I deactivated
- get postgres working
- test all modules: api, frontend, backend

### CODE REVIEW

**Review by sauloperez — COMMENTED** [review]
Great! Let's replace Semaphore's Github integration with the Travis one.

**Review by sauloperez — APPROVED** [review]

**Review by sauloperez — APPROVED** [review]

**Review by sauloperez — CHANGES_REQUESTED** [review]
Sorry, scrap my previous approval. Semaphore was already working and we focused on fixing each of the failing specs, so I believe setting up a different CI and commenting out the failing engines is somehow a step back.

Skipping each of the current failing specs, however, might be a good option to have a green test suite, which lets us move forward, while we spend time fixing them.

thoughts @luisramos0, @Matt-Yorkley, @HugsDaniel ?

**Comment by mkllnk** [comment]
Semaphore was working? When, where? I just see failed builds. I can work on getting Semaphore passing, but I worked on Travis, because Spree had a config for that already and Semaphore wasn't around at the time.

**Comment by mkllnk** [comment]
Closing this in favour of all the work @HugsDaniel is doing at the moment.

**Pull request closed without merging**
